WebApplication/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.IO;

namespace WebApplication.Controllers
{
    public class AdminsController : Controller
    {
        DB_WebEntities dbAdmins = new DB_WebEntities();

        #region Index
        public ActionResult Index()
        {
            return View(dbAdmins.T_Admins);
        }
        #endregion

        #region Dashboard
        public ActionResult Dashboard()
        {
            return View();
        }
        #endregion

        #region Create
        [HttpGet] 
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Name, Family, PhoneNumber, Password, Email, NationalCode, ImageName")] T_Admins admin, HttpPostedFileBase ImageName)
        {
            if (ModelState.IsValid)
            {
                string newImageName = "user.jpg";

                if (ImageName != null)
                {
                    //فیلم بفرسته با فرمت mp4 باگ داره

                    if (ImageName.ContentType != "image/jpeg" && ImageName.ContentType != "image/png")
                    {
                        ModelState.AddModelError("ImageName", "تصویر شما باید با فرمت png یا jpg یا jpeg باشد");
                        return View();
                    }  

                    if (ImageName.ContentLength > 300000)
                    {
                        ModelState.AddModelError("ImageName", "سایز تصویر شما نباید بیشتر از 300 کیلوبایت باشد");
                        return View();
                    }

                    newImageName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(ImageName.FileName);
                    ImageName.SaveAs(Server.MapPath("/Image/Profile/" + newImageName));
                }
                admin.ImageName = newImageName;
                admin.RoleId = 1;
                admin.RegisterDate = DateTime.Now;
                admin.IsActive = true;
                dbAdmins.T_Admins.Add(admin);
                dbAdmins.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Details
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            if (dbAdmins.T_Admins.Find(id)==null)
            {
                return HttpNotFound();
            }
            return View(dbAdmins.T_Admins.Find(id));
        }
        #endregion

    }
}

WebApplication/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class CategoriesController : Controller
    {
        DB_WebEntities dbCategories = new DB_WebEntities();

        #region Index
        public ActionResult Index()
        {
            return View(dbCategories.T_Categories);
        }
        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "CategoryName")] T_Categories category)
        {
            if (ModelState.IsValid)
            {
                category.RegisterAdminId = 13;
                dbCategories.T_Categories.Add(category);
                dbCategories.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbCategories.T_Categories.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbCategories.T_Categories.Find(id));
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, CategoryName, RegisterAdminId")] T_Categories category)
        {
            if (ModelState.IsValid)
            {
                dbCategories.Entry(category).State = EntityState.Modified;
                dbCategories.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Delete
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbCategories.T_Categories.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbCategories.T_Categories.Find(id));
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeletePost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbCategories.T_Categories.Find(id) == null)
            {
                return HttpNotFound();
            }
            var category = dbCategories.T_Categories.Find(id);
            if (category != null)
            {
                dbCategories.T_Categories.Remove(category);
                dbCategories.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }
        #endregion

    }
}

WebApplication/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class RolesController : Controller
    {
        DB_WebEntities dbRoles = new DB_WebEntities();
        #region Index
        public ActionResult Index()
        {
            return View(dbRoles.T_Roles);
        }
        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "RoleName,RoleTitle")] T_Roles role)
        {
            if (ModelState.IsValid)
            {
                dbRoles.T_Roles.Add(role);
                dbRoles.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbRoles.T_Roles.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbRoles.T_Roles.Find(id));
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "RoleId, RoleName, RoleTitle")] T_Roles role)
        {
            if (ModelState.IsValid)
            {
                dbRoles.Entry(role).State = EntityState.Modified;
                dbRoles.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }
        #endregion


        #region Delete
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbRoles.T_Roles.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbRoles.T_Roles.Find(id));
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeletePost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbRoles.T_Roles.Find(id) == null)
            {
                return HttpNotFound();
            }
            var role = dbRoles.T_Roles.Find(id);
            if (role != null)
            {
                dbRoles.T_Roles.Remove(role);
                dbRoles.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }
        #endregion



    }
}

WebApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.IO;
using System.Net;
using System.Data.Entity;
using GSD.Globalization;

namespace WebApplication.Controllers
{
    public class UsersController : Controller
    {
        DB_WebEntities dbUsers = new DB_WebEntities();

        #region Index
        public ActionResult Index()
        {
            return View(dbUsers.T_Users);
        }
        #endregion

        #region Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Name, Family, PhoneNumber, Password, Email, NationalCode,  ImageName")] T_Users user, HttpPostedFileBase ImageName)
        {
            if (ModelState.IsValid)
            {
                string newImageName = "user.jpg";

                if (ImageName != null)
                {

                    if (ImageName.ContentType != "image/jpeg" && ImageName.ContentType != "image/png")
                    {
                        ModelState.AddModelError("ImageName", "تصویر شما باید با فرمت png یا jpg یا jpeg باشد");
                        return View();
                    }

                    if (ImageName.ContentLength > 300000)
                    {
                        ModelState.AddModelError("ImageName", "سایز تصویر شما نباید بیشتر از 300 کیلوبایت باشد");
                        return View();
                    }

                    newImageName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(ImageName.FileName);
                    ImageName.SaveAs(Server.MapPath("/Image/Profile/ProfileUser/" + newImageName));
                }
                user.ImageName = newImageName;
                user.RoleId = 2;
                user.RegisterDate = DateTime.Now;
                user.IsActive = true;
                dbUsers.T_Users.Add(user);
                dbUsers.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        #endregion

        #region Details
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbUsers.T_Users.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbUsers.T_Users.Find(id));
        }
        #endregion

        #region Edit
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbUsers.T_Users.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbUsers.T_Users.Find(id));
        }


        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Name, Family, PhoneNumber, Password, Email, NationalCode, RegisterDate, IsActive, ImageName, RoleId")] T_Users user, HttpPostedFileBase newImageProfile)
        {
            if (ModelState.IsValid)
            {
                if (newImageProfile != null)
                {
                    //فیلم بفرسته با فرمت mp4 باگ داره
                    if (newImageProfile.ContentType != "image/jpeg" && newImageProfile.ContentType != "image/png")
                    {
                        ModelState.AddModelError("ImageName", "تصویر شما باید با فرمت png یا jpg یا jpeg باشد");
                        return View(user);
                    }
                    if (newImageProfile.ContentLength > 300000)
                    {
                        ModelState.AddModelError("ImageName", "سایز تصویر شما نباید بیشتر از 300 کیلوبایت باشد");
                        return View(user);
                    }
                    string newImageName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(newImageProfile.FileName);
                    newImageProfile.SaveAs(Server.MapPath("/Image/Profile/ProfileUser/" + newImageName));
                    user.ImageName = newImageName;
                }
                dbUsers.Entry(user).State = EntityState.Modified;
                dbUsers.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }
        #endregion


        #region Delete
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbUsers.T_Users.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(dbUsers.T_Users.Find(id));
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeletePost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (dbUsers.T_Users.Find(id) == null)
            {
                return HttpNotFound();
            }
            var user = dbUsers.T_Users.Find(id);
            if (user != null)
            {
                dbUsers.T_Users.Remove(user);
                

                if (user.ImageName != "user.png")
                {
                    if (System.IO.File.Exists(Server.MapPath("/Image/Profile/ProfileUser") + user.ImageName))
                    {
                        System.IO.File.Delete(Server.MapPath("/Image/Profile/ProfileUser" + user.ImageName));
                    }
                }
                dbUsers.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }


        #endregion


    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap-rtl.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body class="rtl">

    <nav>
        <ul>
            <li>
                <img src="~/image/Navbar/make-up.png" />
            </li>
            <li>
                <div> <a href="#">صفحه اصلی</a></div>
            </li>

            <li><a href="#">فروشگاه</a></li>

            <li><a href="#">تماس با ما</a></li>
            <li><a href="#">درباره با ما</a></li>

            <li>
                <div>
                    <input type="text" placeholder="جستجو" />
                    <i class="glyphicon glyphicon-search"></i>
                </div>
            </li>
            <li>
                <div>
                    <img src="~/image/Navbar/shopping-cart.png" alt="">
                </div>
            </li>
            <li>
                <div>
                    <img src="~/image/Navbar/user.png" alt="">
                    @Html.ActionLink("ورود | ثبت نام", "Dashboard", "Admins")
                </div>
            </li>
        </ul>
    </nav>


    <div>
        @RenderBody()
    </div>


    <footer>
        <div>
            <ul>
                <li>
                    <h5>خدمات </h5>
                </li>
                <li><a href="#">مشاوره خرید</a></li>
                <li><a href="#">انتقادات و پیشنهادات </a></li>
                <li><a href="#">پرسش های متداول</a></li>

            </ul>
            <ul>
                <li>
                    <h5>تماس با ما</h5>
                </li>
                <li>
                    <i class="glyphicon glyphicon-earphone"></i>
                    <a href="tel:09918915659">09918915659 </a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-envelope"></i>
                    <a href="mailto:info@onlineShop.com">info@onlineShop.com</a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-home"></i>

                    <a href="#">کد پستی : 127433023</a>
                </li>
                <li>
                    <i class="glyphicon glyphicon-road"></i>
                    <a href="#">تهران، خیابان ملاصدرا، خیابان گلدشت، کوچه گلدشت یکم، پلاک 14</a>
                </li>
            </ul>
            <ul>
                <li>
                    <div>
                        <h5>نماد ها</h5>
                        <img src="~/image/Footer/inmad.png" height="185" />
                        <img src="~/image/Footer/zarin-palpng.parspng.com_.png" height="185" />
                    </div>
                </li>
            </ul>
        </div>
    </footer>


    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WebApplication/Views/Shared/_PDashboardRight.cshtml
<div class="dashboard-right">
    <div><img src="~/Image/icon.png" /></div>
    <hr />
    <div>
        <ul>
            <li>
                @Html.ActionLink("داشبورد", "Dashboard", "Admins", null, new { @class = "btn-color" })
            </li>
            <li>
                @Html.ActionLink("دسته بندی ها", "Index", "Categories", null, new { @class = "btn-color" })
            </li>
            <li>
                @Html.ActionLink("محصولات", "Index", "Products", null, new { @class = "btn-color" })
            </li>
            <li>
                @Html.ActionLink("مدیران", "Index", "Admins", null, new { @class = "btn-color" })
            </li>
            <li>
                @Html.ActionLink("کاربران", "Index", "Users", null, new { @class = "btn-color" })
            </li>
            <li>
                @Html.ActionLink("نقش های کاربری", "Index", "Roles", null, new { @class = "btn-color" })
            </li>
            <li>
                <a href="#" class="btn-color">
                    موجودی کالا
                </a>
            </li>
            <li>
                <a href="#" class="btn-color">تنظیمات</a>
            </li>
            <li>
                <a href="#" class="btn-color">خروج</a>
            </li>
        </ul>
    </div>
</div>

WebApplication/Views/Shared/_PDashboardTop.cshtml
<div class="dashboard-top">
    <div>
        <ul>
            <li>داشبورد  |  ناحیه کاربری</li>
            <li>
                <span>جمعه</span>
                <span>13 : 13</span>
                <span>5 / 12 / 1401</span>
            </li>
        </ul>
    </div>
    <div>
        <ul>
            <li class="btn">
                @Html.ActionLink("مشاهده سایت", "Index", "Home",null, new { @class = "btn-color" })


                
            </li>
            <li class="btn">دیدگاه های تایید نشده</li>
            <li class="btn">سفارشات جدید</li>
            <li class="btn">بازدید ها</li>
        </ul>
    </div>
</div>